# Generated by Django 6.0.6 on 2026-06-21 03:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("note", models.TextField(blank=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customers",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["store", "is_deleted"],
                        name="customers_c_store_i_6a0a78_idx",
                    )
                ],
            },
        ),
    ]
